spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/wanted
    username: ENC(4i9WjdaCbIQO9COSr006xQ==)
    password: ENC(hstdvspZSS42bCWZ0hBskGNliLVlyo49)

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 100000
